
export const DREAMS_FETCHING_START = 'DREAMS_FETCHING_START';
export const DREAMS_FETCHING_SUCCESS = 'DREAMS_FETCHING_SUCCESS';
export const DREAMS_FETCHING_ERROR = 'DREAMS_FETCHING_ERROR';
export const MAKE_DREAM_ACTIVE = 'MAKE_DREAM_ACTIVE';
